import "./globals.css";
import { Inter } from "next/font/google";
import { Provider } from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" suppressHydrationWarning>
      <head>
        <title>Daily Muslims</title>
        <meta name="description" content="daily muslims" />
        <meta name="keywords" content="daily muslims" />
      </head>
      <body className={`${inter.className} px-5 bg-[#E3F5F8] dark:bg-gray-900`}>
        <Provider>
          <main className="max-w-md mx-auto">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
